"""Package constants. Import this instead of the package root from engines."""

__version__ = "0.1.0"
IDENTITY = "Aziel Eliab"
SPEC = "azbrowser-phase-1"
LIMITATION = (
    "THIS IS: a Phase 1 research-browser shell (browser-chrome UX) with "
    "controlled fetch/proxy preview, receipted airlock, and Lamb Lens "
    "ethical search. AZNet is a sibling side-net "
    "(https://github.com/AzielEliab/aznet) — AZBrowser views it and "
    "requires pairing to run. THIS IS NOT: a Chromium replacement, a VPN, "
    "AZ-OS, Lumen, AZInterface, or an AZNet protocol fork. FragGate unlocks; "
    "StaticClock times. AZMail is a separate sibling. No receipt = no action. "
    "Author: Aziel Eliab only."
)
RUNTIME = "https://aziel-runtime.vibelock.workers.dev"
FRAGGATE = "https://github.com/AzielEliab/fraggate"
FRAGGATE_CALL = "https://aziel-runtime.vibelock.workers.dev/v1/fraggate/call"
FRAGGATE_MCP = "https://aziel-runtime.vibelock.workers.dev/mcp"
HOST = "https://azbrowser-download-tracker.vibelock.workers.dev"
SIGIL = "https://www.azielcorpuslibrary.net/sigil.png"
AZMAIL = "https://github.com/AzielEliab/azmail"
AZMAIL_WORKER = "https://azmail-download-tracker.vibelock.workers.dev"
AZNET = "https://github.com/AzielEliab/aznet"
AZNET_WORKER = "https://aznet-download-tracker.vibelock.workers.dev"
AZNET_GARDEN = "https://aznet-download-tracker.vibelock.workers.dev/garden"
STATICCLOCK = "https://github.com/AzielEliab/staticclock"
LIBRARY = "https://www.azielcorpuslibrary.net/"
GODLOCK = "https://godlock.uk/"
AUTHOR_SITE = "https://www.azieleliab.com"
GITHUB = "https://github.com/AzielEliab/azbrowser"
