"""Package constants. Import this instead of the package root from engines."""

__version__ = "0.1.0"
IDENTITY = "Aziel Eliab"
SPEC = "azbrowser-phase-1"
LIMITATION = (
    "THIS IS: a Phase 1 research-browser shell (browser-chrome UX) with "
    "controlled fetch/proxy preview, receipted airlock, and Lamb Lens ethical "
    "search. THIS IS NOT: a Chromium/Firefox/Safari replacement, a full OS "
    "browser, a VPN, AZ-OS, Lumen, or AZInterface. v0.1 cannot ship a "
    "Chromium binary. AZMail is a sibling "
    "(https://github.com/AzielEliab/azmail). AZNet is a sibling functional "
    "pair (https://github.com/AzielEliab/aznet) — separate app, not this "
    "protocol. No receipt = no action. Advisory only. Author: Aziel Eliab only."
)
RUNTIME = "https://aziel-runtime.vibelock.workers.dev"
FRAGGATE = "https://github.com/AzielEliab/fraggate"
FRAGGATE_CALL = "https://aziel-runtime.vibelock.workers.dev/v1/fraggate/call"
FRAGGATE_MCP = "https://aziel-runtime.vibelock.workers.dev/mcp"
HOST = "https://azbrowser-download-tracker.vibelock.workers.dev"
SIGIL = "https://www.azielcorpuslibrary.net/sigil.png"
AZMAIL = "https://github.com/AzielEliab/azmail"
AZMAIL_WORKER = "https://azmail-download-tracker.vibelock.workers.dev"
AZNET = "https://github.com/AzielEliab/aznet"
AZNET_WORKER = "https://aznet-download-tracker.vibelock.workers.dev"
LIBRARY = "https://www.azielcorpuslibrary.net/"
GODLOCK = "https://godlock.uk/"
AUTHOR_SITE = "https://www.azieleliab.com"
GITHUB = "https://github.com/AzielEliab/azbrowser"
